import { MigrationInterface, QueryRunner } from "typeorm";

export class Page1777730930144 implements MigrationInterface {
    name = 'Page1777730930144'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` DROP FOREIGN KEY \`fk_user\``);
        await queryRunner.query(`ALTER TABLE \`v4p_jfavorites\` DROP FOREIGN KEY \`FK_9875a04e8a3202424642c8e92d1\``);
        await queryRunner.query(`DROP INDEX \`v4p_jsites1_index_id_club4patas\` ON \`v4p_jsites1\``);
        await queryRunner.query(`DROP INDEX \`idx_jsites1_user_id\` ON \`v4p_jsites1\``);
        await queryRunner.query(`DROP INDEX \`IDX_76f11db054b259832626b25161\` ON \`v4p_juser_profiles\``);
        await queryRunner.query(`DROP INDEX \`IDX_807184bdc32d901b403261d9bc\` ON \`v4p_jlanguages\``);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` DROP COLUMN \`capacity\``);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` DROP COLUMN \`rooms\``);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` DROP COLUMN \`tipenv\``);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` DROP COLUMN \`comodidades\``);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` DROP COLUMN \`exterior\``);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` DROP COLUMN \`familiar\``);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` DROP COLUMN \`actividades\``);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` DROP COLUMN \`experiencia\``);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` DROP COLUMN \`servicios_de_actividad\``);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` DROP COLUMN \`contador_favoritos\``);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` DROP COLUMN \`baños\``);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` DROP COLUMN \`tipo_de_alquiler\``);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`v4p_juser_profiles\` DROP COLUMN \`password\``);
        await queryRunner.query(`ALTER TABLE \`v4p_juser_profiles\` DROP COLUMN \`role\``);
        await queryRunner.query(`ALTER TABLE \`v4p_juser_profiles\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`v4p_jclientes_translations\` ADD \`page\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`name\` \`name\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`fechainscr\` \`fechainscr\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`active\` \`active\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`premium\` \`premium\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`alias_l1\` \`alias_l1\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`poblacio\` \`poblacio\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`alias_poblacio\` \`alias_poblacio\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`provincia\` \`provincia\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`interes\` \`interes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`alias_interes\` \`alias_interes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`email\` \`email\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`email2\` \`email2\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`telefono\` \`telefono\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`destacado\` \`destacado\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`precio\` \`precio\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`tipsite\` \`tipsite\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`tipdest\` \`tipdest\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`tiprent\` \`tiprent\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`tipspec\` \`tipspec\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`tipserv\` \`tipserv\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`cercapn\` \`cercapn\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`cercapl\` \`cercapl\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`cercaru\` \`cercaru\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`cercazr\` \`cercazr\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`cercamm\` \`cercamm\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`distancia\` \`distancia\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`ubicacion\` \`ubicacion\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`suborden\` \`suborden\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`reserva\` \`reserva\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`web\` \`web\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`geolat\` \`geolat\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`geolng\` \`geolng\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`promocion\` \`promocion\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`link_booking\` \`link_booking\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`link_ownbook\` \`link_ownbook\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`code_ownbook\` \`code_ownbook\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`image1\` \`image1\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`password\` \`password\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`accepted\` \`accepted\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`seocaption_l1\` \`seocaption_l1\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`seocaption_l2\` \`seocaption_l2\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`seodescription_l1\` \`seodescription_l1\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`seodescription_l2\` \`seodescription_l2\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_juser_profiles\` ADD UNIQUE INDEX \`IDX_76f11db054b259832626b25161\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`v4p_jtranslation_tables\` CHANGE \`table_name\` \`table_name\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jtranslation_tables\` ADD UNIQUE INDEX \`IDX_2f1eedb0688fd490ba044e489e\` (\`table_name\`)`);
        await queryRunner.query(`ALTER TABLE \`v4p_jtranslation_tables\` DROP COLUMN \`identifier\``);
        await queryRunner.query(`ALTER TABLE \`v4p_jtranslation_tables\` ADD \`identifier\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jtranslation_tables\` CHANGE \`field_name\` \`field_name\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jlanguages\` ADD PRIMARY KEY (\`code\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_10aea321b3016b8b3692aa137e\` ON \`v4p_jclientes_translations\` (\`table_name\`, \`lang\`, \`field\`, \`identifier\`, \`page\`)`);
        await queryRunner.query(`ALTER TABLE \`v4p_jfavorites\` ADD CONSTRAINT \`FK_9875a04e8a3202424642c8e92d1\` FOREIGN KEY (\`site_id\`) REFERENCES \`v4p_jsites1\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`v4p_jfavorites\` DROP FOREIGN KEY \`FK_9875a04e8a3202424642c8e92d1\``);
        await queryRunner.query(`DROP INDEX \`IDX_10aea321b3016b8b3692aa137e\` ON \`v4p_jclientes_translations\``);
        await queryRunner.query(`ALTER TABLE \`v4p_jlanguages\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`v4p_jtranslation_tables\` CHANGE \`field_name\` \`field_name\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jtranslation_tables\` DROP COLUMN \`identifier\``);
        await queryRunner.query(`ALTER TABLE \`v4p_jtranslation_tables\` ADD \`identifier\` varchar(50) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL DEFAULT ''id''`);
        await queryRunner.query(`ALTER TABLE \`v4p_jtranslation_tables\` DROP INDEX \`IDX_2f1eedb0688fd490ba044e489e\``);
        await queryRunner.query(`ALTER TABLE \`v4p_jtranslation_tables\` CHANGE \`table_name\` \`table_name\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_juser_profiles\` DROP INDEX \`IDX_76f11db054b259832626b25161\``);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`seodescription_l2\` \`seodescription_l2\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`seodescription_l1\` \`seodescription_l1\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`seocaption_l2\` \`seocaption_l2\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`seocaption_l1\` \`seocaption_l1\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`accepted\` \`accepted\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`password\` \`password\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`image1\` \`image1\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`code_ownbook\` \`code_ownbook\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`link_ownbook\` \`link_ownbook\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`link_booking\` \`link_booking\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`promocion\` \`promocion\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`geolng\` \`geolng\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`geolat\` \`geolat\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`web\` \`web\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`reserva\` \`reserva\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`suborden\` \`suborden\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`ubicacion\` \`ubicacion\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`distancia\` \`distancia\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`cercamm\` \`cercamm\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`cercazr\` \`cercazr\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`cercaru\` \`cercaru\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`cercapl\` \`cercapl\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`cercapn\` \`cercapn\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`tipserv\` \`tipserv\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`tipspec\` \`tipspec\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`tiprent\` \`tiprent\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`tipdest\` \`tipdest\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`tipsite\` \`tipsite\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`precio\` \`precio\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`destacado\` \`destacado\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`telefono\` \`telefono\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`email2\` \`email2\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`email\` \`email\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`alias_interes\` \`alias_interes\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`interes\` \`interes\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`provincia\` \`provincia\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`alias_poblacio\` \`alias_poblacio\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`poblacio\` \`poblacio\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`alias_l1\` \`alias_l1\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`premium\` \`premium\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`active\` \`active\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`fechainscr\` \`fechainscr\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` CHANGE \`name\` \`name\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jclientes_translations\` DROP COLUMN \`page\``);
        await queryRunner.query(`ALTER TABLE \`v4p_juser_profiles\` ADD \`name\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_juser_profiles\` ADD \`role\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_juser_profiles\` ADD \`password\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` ADD \`user_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` ADD \`tipo_de_alquiler\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` ADD \`baños\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` ADD \`contador_favoritos\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` ADD \`servicios_de_actividad\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` ADD \`experiencia\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` ADD \`actividades\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` ADD \`familiar\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` ADD \`exterior\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` ADD \`comodidades\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` ADD \`tipenv\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` ADD \`rooms\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` ADD \`capacity\` text CHARACTER SET "utf8" COLLATE "utf8_general_ci" NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_807184bdc32d901b403261d9bc\` ON \`v4p_jlanguages\` (\`code\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_76f11db054b259832626b25161\` ON \`v4p_juser_profiles\` (\`email\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_jsites1_user_id\` ON \`v4p_jsites1\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`v4p_jsites1_index_id_club4patas\` ON \`v4p_jsites1\` (\`id_club4patas\`)`);
        await queryRunner.query(`ALTER TABLE \`v4p_jfavorites\` ADD CONSTRAINT \`FK_9875a04e8a3202424642c8e92d1\` FOREIGN KEY (\`site_id\`) REFERENCES \`v4p_jsites1\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`v4p_jsites1\` ADD CONSTRAINT \`fk_user\` FOREIGN KEY (\`user_id\`) REFERENCES \`v4p_juser_profiles\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
    }

}
